services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Taketool\Feuserlist\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Taketool\Feuserlist\Domain\Repository\FrontendUserRepository:
    public: true

  Taketool\Feuserlist\Domain\Repository\FrontendUserGroupRepository:
    public: true
